[project]
name = "orchestration_dagster"
requires-python = ">=3.9.2,<3.15"
version = "0.1.0"
dependencies = [
    "dagster==1.11.16",
    "dlt[duckdb,filesystem,parquet]==1.18.1",
    "dagster-dlt",
    "pyiceberg>=0.6.0",
    "sqlalchemy>=2.0.18",
]

[dependency-groups]
dev = [
    "dagster-webserver",
    "dagster-dg-cli",
    "pytest>=8.4.2",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "pyproject.toml" = "pyproject.toml" }

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "orchestration_dagster"
registry_modules = [
    "orchestration_dagster.components.*",
]


